  #-----------------------------------------------------#
  #           Configuration             #
  #-----------------------------------------------------#
Config:
  #Temps entre chaque give d'item (temps minimum et maximum)
  # en secondes
  MinGiveTime: 1
  MaxGiveTime: 3

  #Est-ce que les messages ci-après seront envoyés a la personne en question ?
  DoNotifyVictimOnBlacklist: true   # Message quand on ajoute quelqu'un a la blacklist d'un GiveAll
  DoNotifyVictimOnUnblacklist: true   # Message quand on retire quelqu'un de la blacklist d'un GiveAll

  #Message quand un joueur ajoute/retire quelqu'un de la blacklist d'un GiveAll
  #PlaceHolders: %{_ga}% pour indiquer le nom du GiveAll
  #PlaceHolders: %{_p}% pour indiquer la personne qui a blacklist/unblacklist
  NotifyVictimOnBlacklist: &cVous avez été blacklist par %{_e}% du GiveAll %{_ga}%
  NotifyVictimOnUnblacklist: &aVous avez été retiré de la blacklist du GiveAll %{_ga}% par %{_e}%

  #Nom de la commande principale
  MainCommand: GiveAll #Peu importe les majuscules/minuscules

  #Nom des alias
  AliasesCommands: ga, givea, gall, give-all #Séparer avec une virgule

  #Son pendant le compte a rebours
  #Liste des sons: https://forum.minecraft-france.fr/threads/16888/
  TimerSound: random.orb

  #-----------------------------------------------------#
  #             Permission            #
  #-----------------------------------------------------#
Permissions:
  #Permissions.
  PermissionAll: giveall.*
  PermissionCreate: giveall.create
  PermissionStart: giveall.start
  PermissionReload: giveall.reload
  PermissionStop: giveall.stop
  PermissionGiveHand: giveall.givehand
  PermissionDelete: giveall.delete
  PermissionAddItem: giveall.additem
  PermissionEditItem: giveall.edititem
  PermissionChatList: giveall.list.chat
  PermissionGUIList: giveall.list.gui
  PermissionRename: giveall.rename
  PermissionHelp: giveall.help
  PermissionUpdateCheck: giveall.updatecheck
  PermissionCopyContent: giveall.copycontent
  PermissionDuplicate: giveall.duplicate
  PermissionClearGA: giveall.clear
  PermissionModify: giveall.modify
  PermissionChangeTime: giveall.settime
  PermissionChangeCountDown: giveall.setcountdown
  PermissionModifyCondition: giveall.condition.modify
  PermissionSeeCondition: giveall.condition.see
  PermissionBypassCondition: giveall.condition.bypass
  PermissionBlackList: giveall.blacklist
  PermissionExemptBlackList:giveall.blacklist.exempt # Ne pas pouvoir être ajouté à la BlackList

  #-----------------------------------------------------#
  #             Log               #
  #-----------------------------------------------------#
Logs:
  #Activer ou désactiver certains logs
  LogCreate: true
  LogStart: true #Quand on fait la commande pour lancer le GiveAll
  LogOnStart: true #Quand le GiveAll se lance
  LogStop: true
  LogReload: true
  LogGiveHand: true
  LogDelete: true
  LogAddItem: true
  LogEditItem: true
  LogListInChat: false
  LogListInGUI: true
  LogRename: true
  LogHelp: false
  LogUpdateCheck: false
  LogCopyContent: true
  LogDuplicate: true
  LogClear: true
  LogModify: true
  LogChangeTime: true
  LogChangeCountDown: true
  LogModifyCondition: true
  LogSeeCondition: true
  LogOnBlacklistAdd: true
  LogOnBlacklistRemove: true
  LogOnBlacklistFailed: true #Quand on blacklist quelqu'un mais qu'il est exempté

  #Chemin d'accès au fichier de log, a partir du fichier "plugins" pour revenir en arrière, faire "../"
  LogPath: giveall/actions.log
